name: Format (PHP)

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
